# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: raidrin
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: sumelu
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sumelu

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    TERMS_TABLE_NAME: ${self:service}-terms-table-${sls:stage}
    OKTA_OAUTH2_ISSUER: ${env:OKTA_OAUTH2_ISSUER}
    OKTA_OAUTH2_AUDIENCE: ${env:OKTA_OAUTH2_AUDIENCE}
  stage: ${opt:stage, 'dev'}
  region: ca-central-1
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-terms-table-${sls:stage}

functions:
  home:
    handler: handler.home
    events:
      - http:
          path: /
          method: get
          cors: true
  globalLearn:
    handler: handler.globalLearn
    events:
      - http:
          path: /global/learn/{term}
          method: get
          cors:
            origin: 'https://sumelu.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
    timeout: 25
  authLearn:
    handler: handler.authLearn
    events:
      - http:
          path: /learn/{term}
          method: get
          cors:
            origin: 'https://sumelu.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
    timeout: 25
  globalDomains:
    handler: handler.globalDomains
    events:
      - http:
          path: /global/domains
          method: get
          cors:
            origin: 'https://sumelu.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

resources:
  Resources:
    TermsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: searchSha
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: searchSha
            KeyType: HASH
        TableName: ${self:service}-terms-table-${sls:stage}

custom:
  customDomain:
    domainName: ${self:provider.stage}-api.sumelu.com
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: sumelu.com # Generated on ACM


plugins:
  - serverless-domain-manager
# POST    /global/learn/${term}
# GET     /global/domains

# POST    /learn/${term}
# GET     /terms/domains
# GET     /terms
# GET     /terms/term/${id}
# DELETE  /terms/term/${id}
